name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_ACCESSTOKEN}}
    - name: Build the Docker image
      run: docker build . --file SongRedirector/Dockerfile --tag mthaller/songredirector:${{ github.sha }}
    - name: Publish image
      if: github.ref == 'refs/heads/master'
      run: docker push mthaller/songredirector:${{ github.sha }}
    - name: 'Login via Azure CLI'
      if: github.ref == 'refs/heads/master'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      if: github.ref == 'refs/heads/master'
      with:
        app-name: 'standupsong'
        images: 'mthaller/songredirector:${{ github.sha }}'
    - name: Azure logout
      if: github.ref == 'refs/heads/master'
      run: |
        az logout
